[Jenkinsfile] Fix repos search in emulator ks file
Signed-off-by: Anastasia Lyupa <a.lyupa@samsung.com>

diff --git a/jenkins/jobs/combirepo_run.jenkinsfile b/jenkins/jobs/combirepo_run.jenkinsfile
--- a/jenkins/jobs/combirepo_run.jenkinsfile
+++ b/jenkins/jobs/combirepo_run.jenkinsfile
@@ -243,48 +243,60 @@ pipeline {
     }
     stage('Build') {
       steps {
-        sh """
-        sudo apt-get install --yes yum python-igraph python-iniparse zlib1g-dev libxml2-dev mic createrepo python-pip qemu-user-static python-configparser python-all dh-make
+        script {
+          unified_repo_name=""
+          unified_asan_repo_name=""
+          if (params.ARCH == "armv7l") {
+            unified_repo_name="unified-standard"
+            unified_asan_repo_name="unified-standard-asan"
+          } else if (params.ARCH == "i686") {
+            unified_repo_name="unified-emulator"
+            unified_asan_repo_name="unified-emulator-asan"
+          }
 
-        sudo ./setup.py build
-        sudo ./setup.py install
+          sh """
+          sudo apt-get install --yes yum python-igraph python-iniparse zlib1g-dev libxml2-dev mic createrepo python-pip qemu-user-static python-configparser python-all dh-make
 
-        wget ${params.KICKSTART_FILE} -O ${ksFile} --user ${OBS_USR} --password ${OBS_PSW}
-        if [ ! -f ${ksFile} ]; then
-            echo "Kickstart file not found!"
-            exit 1
-        fi
+          sudo ./setup.py build
+          sudo ./setup.py install
 
-        unified_repo=`cat ${ksFile} | grep 'repo --name=unified-standard --baseurl=' | egrep -o 'https?://[^ ]+'`
-        unified_asan_repo=`cat ${ksFile} | grep 'repo --name=unified-standard-asan --baseurl=' | egrep -o 'https?://[^ ]+'`
-        base_repo=`cat ${ksFile} | grep 'repo --name=base-standard --baseurl=' | egrep -o 'https?://[^ ]+'`
-        base_asan_repo=`cat ${ksFile} | grep 'repo --name=base-standard-asan --baseurl=' | egrep -o 'https?://[^ ]+'`
+          wget ${params.KICKSTART_FILE} -O ${ksFile} --user ${OBS_USR} --password ${OBS_PSW}
+          if [ ! -f ${ksFile} ]; then
+              echo "Kickstart file not found!"
+              exit 1
+          fi
 
-        if ${params.MIRROR}; then mirror="--mirror"; else mirror=""; fi
-        if ${params.GREEDY}; then greedy="--greedy"; else greedy=""; fi
-        if ${params.DISABLE_RPM_PATCHING}; then rpm_patching="--disable-rpm-patching"; else rpm_patching=""; fi
-        if ${params.DEBUG}; then debug="--debug"; else debug=""; fi
-        if ${params.VERBOSE}; then verbose="--verbose"; else verbose=""; fi
-        if [ ! -z ${params.FORWARD} ]; then forward="-f ${params.FORWARD}"; else forward=""; fi
-        if [ ! -z ${params.BACKWARD} ]; then backward="-b ${params.BACKWARD}"; else backward=""; fi
-        if [ ! -z ${params.SINGLE} ]; then single="-s ${params.SINGLE}"; else single=""; fi
-        if [ ! -z ${params.EXCLUDE} ]; then exclude="-e ${params.EXCLUDE}"; else exclude=""; fi
-        if [ ! -z ${params.PREFERABLE} ]; then preferable="-p ${params.PREFERABLE}"; else preferable=""; fi
+          unified_repo=`cat ${ksFile} | grep 'repo --name=${unified_repo_name} --baseurl=' | egrep -o 'https?://[^ ]+'`
+          unified_asan_repo=`cat ${ksFile} | grep 'repo --name=${unified_asan_repo_name} --baseurl=' | egrep -o 'https?://[^ ]+'`
+          base_repo=`cat ${ksFile} | grep 'repo --name=base-standard --baseurl=' | egrep -o 'https?://[^ ]+'`
+          base_asan_repo=`cat ${ksFile} | grep 'repo --name=base-standard-asan --baseurl=' | egrep -o 'https?://[^ ]+'`
 
-        sudo rm -f ${logFile}
-        mkdir -p ${params.OUTDIR}
-        mkdir -p ${params.CACHEDIR}
+          if ${params.MIRROR}; then mirror="--mirror"; else mirror=""; fi
+          if ${params.GREEDY}; then greedy="--greedy"; else greedy=""; fi
+          if ${params.DISABLE_RPM_PATCHING}; then rpm_patching="--disable-rpm-patching"; else rpm_patching=""; fi
+          if ${params.DEBUG}; then debug="--debug"; else debug=""; fi
+          if ${params.VERBOSE}; then verbose="--verbose"; else verbose=""; fi
+          if [ ! -z ${params.FORWARD} ]; then forward="-f ${params.FORWARD}"; else forward=""; fi
+          if [ ! -z ${params.BACKWARD} ]; then backward="-b ${params.BACKWARD}"; else backward=""; fi
+          if [ ! -z ${params.SINGLE} ]; then single="-s ${params.SINGLE}"; else single=""; fi
+          if [ ! -z ${params.EXCLUDE} ]; then exclude="-e ${params.EXCLUDE}"; else exclude=""; fi
+          if [ ! -z ${params.PREFERABLE} ]; then preferable="-p ${params.PREFERABLE}"; else preferable=""; fi
 
-        sudo combirepo -A ${params.ARCH} -k ${ksFile} --packages-file ${pkgFile} --user ${OBS_USR} --password ${OBS_PSW} -o ${OUTDIR} \
-        -l ${logFile} --tmp-dir ${params.CACHEDIR} -j ${params.JOBS_NUMBER} \
-        \${greedy} \${mirror} \${rpm_patching} \${debug} \${verbose} \
-        --regenerate-repodata --preferring-strategy big --skip-version-mismatch \
-        \${forward} \${backward} \${single} \${exclude} \${preferable} \
-        unified-standard \${unified_repo} \${unified_asan_repo} \
-        unified-standard-asan \${unified_repo} \${unified_asan_repo} \
-        base-standard \${base_repo} \${base_asan_repo} \
-        base-standard-asan \${base_repo} \${base_asan_repo}
-        """
+          sudo rm -f ${logFile}
+          mkdir -p ${params.OUTDIR}
+          mkdir -p ${params.CACHEDIR}
+
+          sudo combirepo -A ${params.ARCH} -k ${ksFile} --packages-file ${pkgFile} --user ${OBS_USR} --password ${OBS_PSW} -o ${OUTDIR} \
+          -l ${logFile} --tmp-dir ${params.CACHEDIR} -j ${params.JOBS_NUMBER} \
+          \${greedy} \${mirror} \${rpm_patching} \${debug} \${verbose} \
+          --regenerate-repodata --preferring-strategy big --skip-version-mismatch \
+          \${forward} \${backward} \${single} \${exclude} \${preferable} \
+          ${unified_repo_name} \${unified_repo} \${unified_asan_repo} \
+          ${unified_asan_repo_name} \${unified_repo} \${unified_asan_repo} \
+          base-standard \${base_repo} \${base_asan_repo} \
+          base-standard-asan \${base_repo} \${base_asan_repo}
+          """
+        }
       }
     }
   }
